version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis_container
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: [ "redis-server", "--appendonly", "yes" ]
    networks:
      - app_network

  postgres:
    image: postgres:latest
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_USER: applicattion_blackist
      POSTGRES_PASSWORD: applicattion_blackist
      POSTGRES_DB: blacklist
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    networks:
      - app_network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq_container
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    ports:
      - "5672:5672" # Porta do protocolo AMQP
      - "15672:15672" # Porta do painel de gerenciamento
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - app_network
  minio:
    container_name: minio_container
    restart: always
    image: minio/minio
    env_file:
      - ./.env
    volumes:
      - data_lake:/data
    ports:
      - 9000:9000
      - 9001:9001
    networks:
      - app_network
    command: server --console-address ":9001" /data
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    ports:
      - "9090:9090"
    networks:
      - app_network

  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - app_network
    depends_on:
      - prometheus

  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    container_name: app_blacklist
    restart: always
    ports:
      - "8000:8000"
    networks:
      - app_network
    depends_on:
      - redis
      - postgres
      - rabbitmq
      - minio
      - grafana
      - prometheus

volumes:
  redis_data:
    driver: local
  postgres_data:
    driver: local
  rabbitmq_data:
    driver: local
  data_lake:
    driver: local
  prometheus_data:
    driver: local
  grafana_data:
    driver: local

networks:
  app_network:
    driver: bridge
